language: python
sudo: false
env:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py27-dj111
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-dj110
  - TOXENV=py34-dj111
  - TOXENV=py34-dj20
  - TOXENV=py36-dj20
  - TOXENV=py34-djdev
  - TOXENV=py36-djdev
  - MOZ_HEADLESS=1
matrix:
  allow_failures:
    - env: TOXENV=py34-djdev
    - env: TOXENV=py36-djdev
install:
  - pip install tox
addons:
  firefox: latest

before_script:
  - export DJANGO_LIVE_TEST_SERVER_ADDRESS=localhost:8000-8010,8080,9200-9300
  - export DJANGO_TEST_PROCESSES=1
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- python manage.py runserver &
  #- sleep 3 # give django server time to bind to sockets
  - sleep 3 # give xvfb some time to start
  # - rackup  # start a Web server
  # - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - tox

#after_success:
#  - coverage combine
#  - codecov
